version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt  
      - run:
          name: Run tests
          command: robot -d results/ tests/

workflows:
  execute-robot-tests: 
    jobs:
      - build-and-test
